CREATE TABLE [dbo].[Training1_11_2022] (
    [data]            NVARCHAR (MAX) NULL,
    [team]            NVARCHAR (MAX) NULL,
    [time]            NVARCHAR (MAX) NULL,
    [Opponent]        NVARCHAR (MAX) NULL,
    [Rank]            NVARCHAR (MAX) NULL,
    [Site]            NVARCHAR (MAX) NULL,
    [Result]          NVARCHAR (MAX) NULL,
    [Attendance]      NVARCHAR (MAX) NULL,
    [CurrentWins]     NVARCHAR (MAX) NULL,
    [CurrentLosses]   NVARCHAR (MAX) NULL,
    [StadiumCapacity] NVARCHAR (MAX) NULL,
    [FillRate]        NVARCHAR (MAX) NULL,
    [NewCoach]        NVARCHAR (MAX) NULL,
    [Tailgating]      NVARCHAR (MAX) NULL
);

